version: '3.8'

services:
  pippastoes:
    build: .
    container_name: pippastoes
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      SOURCE_CHANNEL_ID: ${SOURCE_CHANNEL_ID}
      DESTINATION_CHANNEL_ID: ${DESTINATION_CHANNEL_ID}
    volumes:
      - pippastoes_logs:/app/logs

volumes:
  pippastoes_logs:
