version: '3.8'
services:
  link-mover:
    image: link-mover-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SOURCE_CHANNEL_ID=${SOURCE_CHANNEL_ID}
      - DESTINATION_CHANNEL_ID=${DESTINATION_CHANNEL_ID}
    volumes:
      - link-mover-logs:/app/logs
      - link-mover-data:/app/data
    restart: unless-stopped
volumes:
  link-mover-logs:
    name: link-mover-logs
  link-mover-data:
    name: link-mover-data
